### ISSUE TITLE
adds metacontent

### ISSUE THREAD

**Issue by fjsousa** [giuliamml/giuliamml.github.io#9]
![Screenshot from 2020-07-27 20-32-13](https://user-images.githubusercontent.com/4125060/88583581-57f33200-d048-11ea-9a4c-0c1d4edf7186.png)

if you compare with this 

![Screenshot from 2020-07-27 20-34-15](https://user-images.githubusercontent.com/4125060/88583756-94bf2900-d048-11ea-82d5-e3bce41c3479.png)

there's an image!

this is done with metatags - it's an html tag that goes in the head

![Screenshot from 2020-07-27 20-35-23](https://user-images.githubusercontent.com/4125060/88583884-bddfb980-d048-11ea-97d4-23678886894e.png)

https://cdn-images-1.medium.com/max/1200/1*29XAq2WrtejUCxRzSgDLXA.png

see og:image?

**Comment by giuliamml** [comment]
Will add it later x

**Comment by fjsousa** [comment]
Add your picture, it just because ppl click if there’s a picure

Flávio Sousa
datajournal.co.uk
00447481958702

**Comment by fjsousa** [comment]
![Screenshot from 2020-08-14 16-55-20](https://user-images.githubusercontent.com/4125060/90268461-f7893080-de4e-11ea-8e05-06ebca45da9a.png)

not there yet

**Comment by giuliamml** [comment]
<img width="720" alt="Screenshot 2020-08-14 at 17 20 07" src="https://user-images.githubusercontent.com/52887737/90270687-7b90e780-de52-11ea-95c1-07a511ad5ff4.png">

these are the meta tags I've added. 
resized the image too but still not working on Whatsapp

**Comment by fjsousa** [comment]
fb as well
